---

- hosts: server
  tasks:

    - name: Import Docker CE repository gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add deb repository
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present

    - name: Ensure that Aptitude repositories are up to date
      apt: update_cache=yes cache_valid_time={{ aptcachetime }}

    - name: Install Docker-ce
      apt: pkg=docker-ce state=latest update_cache=yes

    - name: Install docker-compose
      get_url: url="https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64" dest=/usr/local/bin/docker-compose force=no mode=0755
      tags:
        - felpete
  
    - name: Install ctop
      get_url: url="https://github.com/bcicen/ctop/releases/download/v0.6.1/ctop-0.6.1-linux-amd64" dest=/usr/local/bin/ctop force=no mode=0777     

    - name: Create Docker dirs for containers
      file: path="/home/docker" state=directory mode="0755"
